HUMAN = 'Human'
GOOGLE = 'Google'
APERTIUM = 'Apertium'
MECHANICAL_TURK = 'Mechanical Turk'

TRANSLATORS = (
    (HUMAN, HUMAN),
    (GOOGLE, GOOGLE),
    (APERTIUM, APERTIUM),
    (MECHANICAL_TURK, MECHANICAL_TURK),
)

DEFAULT_TRANNY = GOOGLE
